{{- range $name, $overrides := .Values.instances }}
{{- $settings := mustMergeOverwrite (dict) (deepCopy $.Values.defaults) $overrides}}
{{- $ctx := dict "name" $name "Release" $.Release "Values" $.Values }}
{{- $resourceName := include "node-red-gitops.resourceName" $ctx }}
{{- if $settings.loadbalancer }}
---
apiVersion: v1
kind: Service
metadata:
  name: '{{ include "node-red-gitops.loadbalancerName" $ctx }}'
{{- if $settings.loadbalancer.annotations }}
  annotations:
  {{- range $key, $value := $settings.loadbalancer.annotations }}
    {{ $key }}: {{ $value | squote }}
  {{- end }}
{{- end }}
  labels:
    app.kubernetes.io/instance: '{{ $name }}'
    app.kubernetes.io/name: '{{ include "node-red-gitops.loadbalancerName" $ctx }}'
spec:
  ports:
    - name: loadbalancer
      port: {{ $settings.loadbalancer.port }}
      protocol: {{ $settings.loadbalancer.protocol }}
      targetPort: {{ $settings.loadbalancer.targetPort }}
  selector:
    app.kubernetes.io/instance: '{{ $name }}'
    app.kubernetes.io/name: '{{ $resourceName }}'
  type: LoadBalancer
  loadBalancerIP: {{ $settings.loadbalancer.ip }}

{{- end -}}
{{- end -}}
