{{- range $name, $overrides := .Values.instances }}
{{- $settings := mustMergeOverwrite (dict) (deepCopy $.Values.defaults) $overrides}}
{{- $ctx := dict "name" $name "Release" $.Release "Values" $.Values }}
{{- $resourceName := include "node-red-gitops.resourceName" $ctx }}
---
apiVersion: v1
kind: Secret
metadata:
  name: '{{ include "node-red-gitops.secretName" $ctx }}'
  labels:
    app.kubernetes.io/instance: '{{ $name }}'
    app.kubernetes.io/name: '{{ $resourceName }}'
type: Opaque
data:
{{- range $key, $value := $settings.projects.secrets }}
  {{ $key }}: {{ printf "%s" $value | b64enc}}
{{- end }}
{{- range $key, $value := $settings.secrets }}
  {{ $key }}: {{ printf "%s" $value | b64enc}}
{{- end }}

{{- end -}}
