{{- range $name, $overrides := .Values.instances }}
{{- $settings := mustMergeOverwrite (dict) (deepCopy $.Values.defaults) $overrides}}
---
apiVersion: v1
kind: Secret
metadata:
  name: '{{ $name }}-{{ $.Release.Name }}-secret'
  labels:
    app.kubernetes.io/instance: '{{ $name }}'
    app.kubernetes.io/name: '{{ $name }}-{{ $.Release.Name }}'
type: Opaque
data:
{{- range $key, $value := $settings.projects.secrets }}
  {{ $key }}: {{ printf "%s" $value | b64enc}}
{{- end }}
{{- range $key, $value := $settings.secrets }}
  {{ $key }}: {{ printf "%s" $value | b64enc}}
{{- end }}

{{- end -}}
