defaults:
  ingress:
    enabled: false

  image: nodered/node-red
  tag: 3.0.2  # renovate: datasource=github-releases depName=node-red packageName=node-red/node-red-docker
  replicas: 1
  timezone: Australia/Sydney
  projects:
    enabled: false
  safe_mode: false
  codeServer:
    enabled: false
  secrets:
    TEST_SECRET: "123"
    TEST_SECRET2: "456"
  env:
    GLOBAL_ENV_VAR: "default-value"
    LOG_LEVEL: "info"
  persistence:
    enabled: false

instances:
  example-1:
    replicas: 1
    timezone: UTC
    secrets:
      TEST_SECRET2: "789"
      TEST_SECRET3: "321"
    env:
      INSTANCE_SPECIFIC_VAR: "instance-value"
      API_URL: "https://api.example.com"
